In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
my_transaction=np.array([40,500,60,400,250])
print(my_transaction)

# version function
print(np.__version__)

[ 40 500  60 400 250]
1.20.3


In [8]:
print(np._version_)

AttributeError: module 'numpy' has no attribute '_version_'

In [9]:
print(np.__version__)

1.20.3


In [11]:
print(type(my_transaction))
print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
# pass tuple to array() methodn
# array method retuns list
mom=np.array((2,3,10,5,8,23,19))
print(mom)

# 0 dimension array
arr=np.array(310)

print("no of dimentions:",arr.ndim)
print(arr)

# 1 d array
b=np.array([3,6,8,9,24])

print("no of dimentions:",b.ndim)
print(b)


# 2D array
c=np.array([[3,4,5],[2,2.3,7]])

print("no of dimentions:",c.ndim)
print(c)

# 3D array
d=np.array([[[3,8,9],[41,4,35]],[[0,1,99],[56,87,0]]])

print("no of dimentions:",d.ndim)
print(d)

[ 2  3 10  5  8 23 19]
no of dimentions: 0
310
no of dimentions: 1
[ 3  6  8  9 24]
no of dimentions: 2
[[3.  4.  5. ]
 [2.  2.3 7. ]]
no of dimentions: 3
[[[ 3  8  9]
  [41  4 35]]

 [[ 0  1 99]
  [56 87  0]]]


In [20]:
# number of dimesion OF ARRY
print(arr.ndim)


print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [26]:
# HIGHER DIMENSIONS
a=np.array([2,4,3,8,10],ndmin=5)
print("array dimenstion:",a.ndim)
print(a)

b=np.array([4,8,5],ndmin=3)
print("array dimension:",b.ndim)
print(b)

array dimenstion: 5
[[[[[ 2  4  3  8 10]]]]]
array dimension: 3
[[[4 8 5]]]


In [27]:
#indexing
print(arr)
print(arr[0])

310


IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [30]:
print(my_transaction)
print(my_transaction[1])
print(my_transaction[0])
print(my_transaction[6])

[ 40 500  60 400 250]
500
40


IndexError: index 6 is out of bounds for axis 0 with size 5

In [37]:
print(c)
print(c[0])
print(c[1])
print(c[1][0])
print(c[-1])
print(c[-2])

[[3.  4.  5. ]
 [2.  2.3 7. ]]
[3. 4. 5.]
[2.  2.3 7. ]
2.0
[2.  2.3 7. ]
[3. 4. 5.]


In [4]:
import numpy as np
arr=np.array([2,3,8,28,23,10])
print(arr)

#indexing
print("add 2 3 indexes")
print(arr[2]+arr[3])


[ 2  3  8 28 23 10]
add 2 3 indexes
36


In [12]:
sis = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element  on 1 row")
print(sis[0,1])

print("5 th element on 2nd row")
print(sis[1,4])

print("negative indexing")
print(sis[1,-1])

print("2nd row")
print(sis[-1])
               

2nd element  on 1 row
2
5 th element on 2nd row
10
negative indexing
10
2nd row
[ 6  7  8  9 10]


In [10]:
print("3d array")
mom = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("first 2d array")
print(mom[0])
print("in 2nd 2d array 1st row")
print(mom[1,0])

print("in 1st 2d array ,2nd row 3 rd element")
print(mom[0,1,2])

print("1,1")
print(mom[1,1])

print("1,1,2")
print(mom[1,1,2])

print("0,1,0")
print(mom[0,1,0])

3d array
first 2d array
[[1 2 3]
 [4 5 6]]
in 2nd 2d array 1st row
[7 8 9]
in 1st 2d array ,2nd row 3 rd element
6
1,1
[10 11 12]
1,1,2
12
0,1,0
4


In [14]:
import numpy as np
print(np.__version__)

print(np.show_config())



1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/ana

In [15]:
# get help on add function
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [16]:
#checking all element if there is one element 0
x=np.array([1,2,3,4])
print("orignal array:")
print(x)

print("test if none of the elements of the said  array is zero:")
print(np.all(x))


x=np.array([0,3,8,9])
print("original array:")

print("test if none of the elements of the said array is zero:")
print(np.all(x))

orignal array:
[1 2 3 4]
test if none of the elements of the said  array is zero:
True
original array:
test if none of the elements of the said array is zero:
False


In [17]:
# cheking non zeros
y=np.array([1,0,0,0])
print("original array:")
print(y)

print("test whether anyone of the element of given array is non-zeros:")
print(np.any(y))

y=np.array([0,0,0,0])
print("original array:")
print("test any one whether any of the element is non-zeros")
print(np.any(y))

original array:
[1 0 0 0]
test whether anyone of the element of given array is non-zeros:
True
original array:
test any one whether any of the element is non-zeros
False


In [19]:
a=np.array([1,0,np.nan,np.inf])
print("original array: ")
print(a)

print("test a given  array elements wise for finiteness:")
print(np.isfinite(a))

original array: 
[ 1.  0. nan inf]
test a given  array elements wise for finiteness:
[ True  True False False]


In [23]:
a=np.array([2,0,np.nan,np.inf])
print("original array")
print(a)

print("test element wiese for positive or  negitive infinity:")
print(np.isinf(a))

b=np.array([-4,np.nan,np.inf,np.inf])
print("array b:")
print(b)
print(np.isinf(b))

original array
[ 2.  0. nan inf]
test element wiese for positive or  negitive infinity:
[False False False  True]
array b:
[-4. nan inf inf]
[False False  True  True]


In [1]:
import numpy as np
# program to test nan values
a=np.array([10,np.nan,np.inf])
print("orinal array")
print(a)
print("test elements for nan values")
print(np.isnan(a))

orinal array
[10. nan inf]
test elements for nan values
[False  True False]


In [3]:
m=np.array([2+5j,4+0j,5,43,6+7j])
print("original array:")
print(m)

print("checking for complex number:")
print(np.iscomplex(m))

print("cheking for real number:")
print(np.isreal(m))

print("cheking for scalar:")
print(np.isscalar(3.1))

print(np.isscalar([3.1]))

original array:
[ 2.+5.j  4.+0.j  5.+0.j 43.+0.j  6.+7.j]
checking for complex number:
[ True False False False  True]
cheking for real number:
[False  True  True  True False]
cheking for scalar:
True
False


In [4]:
#tolerence
import numpy as np

print("test if two arrays are elements equal with in a tolarence")

print(np.allclose([1e10,1e-7],[100001e10,1e-8]))
print(np.allclose([1e10,1e-8],[100001e10,1e-9]))
print(np.allclose([1e10,1e-8],[10001e10,1e-9]))
print(np.allclose([1.0,np.nan],[1.0,np.nan]))
print(np.allclose([1.0,np.nan],[1.0,np.nan],equal_nan=True))

test if two arrays are elements equal with in a tolarence
False
False
False
False
True


In [7]:
x=np.array([1,7,13,105])
print("original array:")
print(x)


print("no of bytes occupied by each elemet")
print(x.itemsize)

print("size of the me(mory )occupied by array:")
print("%d bytes",(x.size * x.itemsize))

print("%d bytes" % (x.size * x.itemsize))


original array:
[  1   7  13 105]
no of bytes occupied by each elemet
4
size of the me(mory )occupied by array:
%d bytes 16
16 bytes


In [16]:
#array of 1,0,5s
print("an array of 10 zeros:")

sa=np.zeros(10)
print(sa)

sa2=np.ones(10)
print("arrayof 10 1 s:")
print(sa2)

print("array of 10 5's:")
sa3=np.ones(10)*5
print(sa3)

print("array of 10 8's")
sa4=np.ones(10)*8
print(sa4)

su=np.array([sa,sa2,sa3,sa4])
print(su)
print("arange in 2x2 ")
print(su.reshape(2,2))

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
arrayof 10 1 s:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 5's:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
array of 10 8's
[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]
arange in 2x2 


ValueError: cannot reshape array of size 40 into shape (2,2)

In [22]:
arr=np.arange(30,71)
print("array of the integer from 30 -70")
print(arr)

print("arnge in 4x10")
print(arr.reshape(4,10))

array of the integer from 30 -70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
arnge in 4x10


ValueError: cannot reshape array of size 41 into shape (4,10)

In [23]:
arr=np.arange(30,70)
print("array of the integer from 30 -70")
print(arr)

print("arnge in 4x10")
print(arr.reshape(4,10))

array of the integer from 30 -70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
arnge in 4x10
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [26]:
nanna=np.arange(30,71,2)
print("array of all even itegers from 30-70")
print(nanna)

mom=np.arange(31,71,2)
print("array of all odd integers from 30-70")
print(mom)

array of all even itegers from 30-70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
array of all odd integers from 30-70
[31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69]


In [27]:
import numpy as np
arr2d=np.identity(3)
print("3x3 matrix")
print(arr2d)



3x3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import numpy as np
g=np.array((3,4,5))
print(g)
print(type(g))

[3 4 5]
<class 'numpy.ndarray'>
