In [3]:
import numpy as np
a=np.array([1,2,3,23,14])
print(a)

#CREATING ARRAY USING LIST
l1=[2,3,8]
l2=[33,11,19]
l3=[7,8,14]
a2=np.array([l1,l2,l3])
print(a2)

print("dimention of a2")
print(a2.ndim)

[ 1  2  3 23 14]
[[ 2  3  8]
 [33 11 19]
 [ 7  8 14]]
dimention of a2
2


In [6]:
# arrange 10 numbers
print("arrange 10 numbers ")
b=np.arange(10)
print(b)

print("arrange 9 numbers ")
c=np.arange(9)
print(c)



arrange 10 numbers 
[0 1 2 3 4 5 6 7 8 9]
arrange 9 numbers 
[0 1 2 3 4 5 6 7 8]


In [7]:
#reshape
print("reshape of3,3")
print(a3.reshape(3,3))
print(a3)

reshape of3,3


NameError: name 'a3' is not defined

In [12]:
#reshape
print("reshape of3,3")
print(c.reshape(3,3))
print("after reshape ORIGINAL array not changed")
print(c)

print("reshape of 2,5")
print(b.reshape(2,5))
print(b)

reshape of3,3
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
reshape of 2,5
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [1]:
import numpy as np
dp=np.arange(9)
print(dp)


print(dp.resize(3,3))
print(dp)



print("resize changes ORIGINAL array" )
print(dp)

[0 1 2 3 4 5 6 7 8]
None
[[0 1 2]
 [3 4 5]
 [6 7 8]]
resize changes ORIGINAL array
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
print(dp)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
import numpy as np
dp=np.arange(9)
print(dp)

a4=np.arange(0,20,2)
print(a4)

a4.shape=(5,2)
print(a4)

print("dimentions of a4")
print(a4.ndim)

print("shape of a4")
print(a4.shape)

print("size of a")
print(a4.size)

print("itemsize means no of bytes of each element")
print(a4.itemsize)

print("data type of a4")
print(a4.dtype)

print("data a4")
print(a4.data)


[0 1 2 3 4 5 6 7 8]
[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
dimentions of a4
2
shape of a4
(5, 2)
size of a
10
itemsize
4
data type of a4
int32
data a4


In [6]:
type(a4)

numpy.ndarray

In [11]:
print(np.zeros((2,3)))

print(np.zeros((3,3)))

print(np.ones((3,2)))

print(np.ones((4,5)))



[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
print(np.empty())

TypeError: empty() missing required argument 'shape' (pos 1)

In [15]:
print(np.empty((3,4)))

[[1.13710371e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [2.22521510e-306 2.92966904e-033 7.17713721e-091 4.31795927e-061]
 [4.31821937e-038 5.93876662e-038 3.99910963e+252 2.52871062e-052]]


In [16]:
print(np.empty((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
print(np.linspace(0,10,5))

print(np.linspace(1,10,4))

print(np.linspace(1,10,2))
print(np.linspace(1,10,0))

[ 0.   2.5  5.   7.5 10. ]
[ 1.  4.  7. 10.]
[ 1. 10.]
[]


In [30]:
print(a4)
print(np.sum(a4))

c=np.arange(0,6)
print(c)
print(np.sum(c))

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
90
[0 1 2 3 4 5]
15
