In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
my_transaction=np.array([40,500,60,400,250])
print(my_transaction)

# version function
print(np.__version__)

[ 40 500  60 400 250]
1.20.3


In [8]:
print(np._version_)

AttributeError: module 'numpy' has no attribute '_version_'

In [9]:
print(np.__version__)

1.20.3


In [11]:
print(type(my_transaction))
print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
# pass tuple to array() methodn
# array method retuns list
mom=np.array((2,3,10,5,8,23,19))
print(mom)

# 0 dimension array
arr=np.array(310)

print("no of dimentions:",arr.ndim)
print(arr)

# 1 d array
b=np.array([3,6,8,9,24])

print("no of dimentions:",b.ndim)
print(b)


# 2D array
c=np.array([[3,4,5],[2,2.3,7]])

print("no of dimentions:",c.ndim)
print(c)

# 3D array
d=np.array([[[3,8,9],[41,4,35]],[[0,1,99],[56,87,0]]])

print("no of dimentions:",d.ndim)
print(d)

[ 2  3 10  5  8 23 19]
no of dimentions: 0
310
no of dimentions: 1
[ 3  6  8  9 24]
no of dimentions: 2
[[3.  4.  5. ]
 [2.  2.3 7. ]]
no of dimentions: 3
[[[ 3  8  9]
  [41  4 35]]

 [[ 0  1 99]
  [56 87  0]]]


In [20]:
# number of dimesion OF ARRY
print(arr.ndim)


print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [26]:
# HIGHER DIMENSIONS
a=np.array([2,4,3,8,10],ndmin=5)
print("array dimenstion:",a.ndim)
print(a)

b=np.array([4,8,5],ndmin=3)
print("array dimension:",b.ndim)
print(b)

array dimenstion: 5
[[[[[ 2  4  3  8 10]]]]]
array dimension: 3
[[[4 8 5]]]


In [27]:
#indexing
print(arr)
print(arr[0])

310


IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [30]:
print(my_transaction)
print(my_transaction[1])
print(my_transaction[0])
print(my_transaction[6])

[ 40 500  60 400 250]
500
40


IndexError: index 6 is out of bounds for axis 0 with size 5

In [37]:
print(c)
print(c[0])
print(c[1])
print(c[1][0])
print(c[-1])
print(c[-2])

[[3.  4.  5. ]
 [2.  2.3 7. ]]
[3. 4. 5.]
[2.  2.3 7. ]
2.0
[2.  2.3 7. ]
[3. 4. 5.]


In [4]:
import numpy as np
arr=np.array([2,3,8,28,23,10])
print(arr)

#indexing
print("add 2 3 indexes")
print(arr[2]+arr[3])


[ 2  3  8 28 23 10]
add 2 3 indexes
36


In [12]:
sis = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element  on 1 row")
print(sis[0,1])

print("5 th element on 2nd row")
print(sis[1,4])

print("negative indexing")
print(sis[1,-1])

print("2nd row")
print(sis[-1])
               

2nd element  on 1 row
2
5 th element on 2nd row
10
negative indexing
10
2nd row
[ 6  7  8  9 10]


In [10]:
print("3d array")
mom = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("first 2d array")
print(mom[0])
print("in 2nd 2d array 1st row")
print(mom[1,0])

print("in 1st 2d array ,2nd row 3 rd element")
print(mom[0,1,2])

print("1,1")
print(mom[1,1])

print("1,1,2")
print(mom[1,1,2])

print("0,1,0")
print(mom[0,1,0])

3d array
first 2d array
[[1 2 3]
 [4 5 6]]
in 2nd 2d array 1st row
[7 8 9]
in 1st 2d array ,2nd row 3 rd element
6
1,1
[10 11 12]
1,1,2
12
0,1,0
4


In [14]:
import numpy as np
print(np.__version__)

print(np.show_config())



1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Keerthy Chawla/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Keerthy Chawla/ana

In [15]:
# get help on add function
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [16]:
#checking all element if there is one element 0
x=np.array([1,2,3,4])
print("orignal array:")
print(x)

print("test if none of the elements of the said  array is zero:")
print(np.all(x))


x=np.array([0,3,8,9])
print("original array:")

print("test if none of the elements of the said array is zero:")
print(np.all(x))

orignal array:
[1 2 3 4]
test if none of the elements of the said  array is zero:
True
original array:
test if none of the elements of the said array is zero:
False


In [17]:
# cheking non zeros
y=np.array([1,0,0,0])
print("original array:")
print(y)

print("test whether anyone of the element of given array is non-zeros:")
print(np.any(y))

y=np.array([0,0,0,0])
print("original array:")
print("test any one whether any of the element is non-zeros")
print(np.any(y))

original array:
[1 0 0 0]
test whether anyone of the element of given array is non-zeros:
True
original array:
test any one whether any of the element is non-zeros
False


In [19]:
a=np.array([1,0,np.nan,np.inf])
print("original array: ")
print(a)

print("test a given  array elements wise for finiteness:")
print(np.isfinite(a))

original array: 
[ 1.  0. nan inf]
test a given  array elements wise for finiteness:
[ True  True False False]


In [23]:
a=np.array([2,0,np.nan,np.inf])
print("original array")
print(a)

print("test element wiese for positive or  negitive infinity:")
print(np.isinf(a))

b=np.array([-4,np.nan,np.inf,np.inf])
print("array b:")
print(b)
print(np.isinf(b))

original array
[ 2.  0. nan inf]
test element wiese for positive or  negitive infinity:
[False False False  True]
array b:
[-4. nan inf inf]
[False False  True  True]


In [1]:
import numpy as np
# program to test nan values
a=np.array([10,np.nan,np.inf])
print("orinal array")
print(a)
print("test elements for nan values")
print(np.isnan(a))

orinal array
[10. nan inf]
test elements for nan values
[False  True False]


In [3]:
m=np.array([2+5j,4+0j,5,43,6+7j])
print("original array:")
print(m)

print("checking for complex number:")
print(np.iscomplex(m))

print("cheking for real number:")
print(np.isreal(m))

print("cheking for scalar:")
print(np.isscalar(3.1))

print(np.isscalar([3.1]))

original array:
[ 2.+5.j  4.+0.j  5.+0.j 43.+0.j  6.+7.j]
checking for complex number:
[ True False False False  True]
cheking for real number:
[False  True  True  True False]
cheking for scalar:
True
False


In [4]:
#tolerence
import numpy as np

print("test if two arrays are elements equal with in a tolarence")

print(np.allclose([1e10,1e-7],[100001e10,1e-8]))
print(np.allclose([1e10,1e-8],[100001e10,1e-9]))
print(np.allclose([1e10,1e-8],[10001e10,1e-9]))
print(np.allclose([1.0,np.nan],[1.0,np.nan]))
print(np.allclose([1.0,np.nan],[1.0,np.nan],equal_nan=True))

test if two arrays are elements equal with in a tolarence
False
False
False
False
True


In [7]:
x=np.array([1,7,13,105])
print("original array:")
print(x)


print("no of bytes occupied by each elemet")
print(x.itemsize)

print("size of the me(mory )occupied by array:")
print("%d bytes",(x.size * x.itemsize))

print("%d bytes" % (x.size * x.itemsize))


original array:
[  1   7  13 105]
no of bytes occupied by each elemet
4
size of the me(mory )occupied by array:
%d bytes 16
16 bytes


In [16]:
#array of 1,0,5s
print("an array of 10 zeros:")

sa=np.zeros(10)
print(sa)

sa2=np.ones(10)
print("arrayof 10 1 s:")
print(sa2)

print("array of 10 5's:")
sa3=np.ones(10)*5
print(sa3)

print("array of 10 8's")
sa4=np.ones(10)*8
print(sa4)

su=np.array([sa,sa2,sa3,sa4])
print(su)
print("arange in 2x2 ")
print(su.reshape(2,2))

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
arrayof 10 1 s:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 5's:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
array of 10 8's
[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]
arange in 2x2 


ValueError: cannot reshape array of size 40 into shape (2,2)

In [1]:
arr=np.arange(30,71)
print("array of the integer from 30 -70")
print(arr)
print(type(arr))

print("arnge in 4x10")
print(arr.reshape(4,10))

NameError: name 'np' is not defined

In [23]:
arr=np.arange(30,70)
print("array of the integer from 30 -70")
print(arr)

print("arnge in 4x10")
print(arr.reshape(4,10))

array of the integer from 30 -70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
arnge in 4x10
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [26]:
nanna=np.arange(30,71,2)
print("array of all even itegers from 30-70")
print(nanna)

mom=np.arange(31,71,2)
print("array of all odd integers from 30-70")
print(mom)

array of all even itegers from 30-70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
array of all odd integers from 30-70
[31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69]


In [27]:
import numpy as np
arr2d=np.identity(3)
print("3x3 matrix")
print(arr2d)



3x3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np
x=np.array([3,5])
y=np.array([2,5])

print("original numbers")
print(x)
print(y)

print("comparision-grater")
print(np.greater(x,y))


print("comparision-grater_equal")
print(np.greater_equal(x,y))

print("comparision-lesser")
print(np.less(x,y))

print("comparision-lesser_equal")
print(np.less_equal(x,y))


original numbers
[3 5]
[2 5]
comparision-grater
[ True False]
comparision-grater_equal
[ True  True]
comparision-lesser
[False False]
comparision-lesser_equal
[False  True]


In [6]:
r=np.array((8,9))
s=np.array((11,3))

print(r)
print(s)

print("greater")
print(np.greater(r,s))
print(np.greater(s,r))

print("greater or equal")
print(np.greater_equal(r,s))
print(np.greater_equal(s,r))

print("less")
print(np.less(r,s))

print("less or equal")
print(np.less_equal(s,s))

[8 9]
[11  3]
greater
[False  True]
[ True False]
greater or equal
[False  True]
[ True False]
less
[ True False]
less or equal
[ True  True]


In [14]:
ran_num=np.random.normal((0,1,1))
print("printing random values betwen 0-1")
print(ran_num)

an_num=np.random.normal(0,1,2)
print("printing random values betwen 0-1")
print(ran_num)

t=np.random.normal(5,6,1)
print(t)

n_num=np.random.normal(10,11,1)
print("printing random values betwen 10-11")
print(n_num)

t=np.random.normal(5,6,3)
print("printing 3 random values betwen 15-6")
print(t)


printing random values betwen 0-1
[0.74256129 1.73625912 1.67834917]
printing random values betwen 0-1
[0.74256129 1.73625912 1.67834917]
[-2.98277441]
printing random values betwen 10-11
[10.48342666]
printing 3 random values betwen 15-6
[9.58919116 3.55696628 3.68835965]


In [15]:
print("15 random values in between 0-1 from a standard normal distibution")
surya=np.random.normal(0,1,15)
print(surya)

15 random values in between 0-1 from a standard normal distibution
[-0.6424095   0.82205299 -1.50877285  0.69775242 -0.58647837  2.487996
 -0.94221985 -1.25615724 -0.89265085  1.08626934  0.46312857 -0.25626251
  0.38741936 -2.28730668  0.86775538]


In [2]:
import numpy as np
f=np.array(3,10,8)
print(f)
print(type(f))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [3]:
v=np.arange(15,55)
print("original vector:")
print(v)

print("printing vector except 1st and last element")
print(v[1:-1])

original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
printing vector except 1st and last element
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [6]:
sis=np.arange(10,22).reshape((3,4))
print("original array")

print(sis)

print("each element of array is:")
for x in np.nditer(sis):
    print(x,end=" ")

original array
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
each element of array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [4]:
import numpy as np
v=np.linspace(10,49,5)
print("length 10 with values distributed between 5 50:")
print(v)

n=np.linspace(5,50,5)
print(" length 5 with values distributed between 5 50")
print(n)

length 10 with values distributed between 5 50:
[10.   19.75 29.5  39.25 49.  ]
 length 5 with values distributed between 5 50
[ 5.   16.25 27.5  38.75 50.  ]


In [8]:
x=np.arange(21)
print("orinal vector:")
print(x)

print("after changeing the sign of the number in the range from 9-15")

x[(x >= 9) & (x <= 15)] *= -1
print(x)

y=np.arange(20)
y[(y >= 4) & (y <= 12)] = -1
print(y)

orinal vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
after changeing the sign of the number in the range from 9-15
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]
[ 0  1  2  3 -1 -1 -1 -1 -1 -1 -1 -1 -1 13 14 15 16 17 18 19]


In [2]:
import numpy as np
x=np.random.randint(0,11,5)
print("vector of length 5 filled witharbitary from 0 to10")
print(x)

vector of length 5 filled witharbitary from 0 to10
[ 1  5  8 10  2]


In [4]:
import numpy as np
x=np.array([1,8,3,5])
print("vector-1")
print(x)

y=np.random.randint(0,11,4)
print("vector-2")
print(y)

result=x*y

print("multiply the values of two said vectors:")
print(result)

vector-1
[1 8 3 5]
vector-2
[9 1 1 3]
multiply the values of two said vectors:
[ 9  8  3 15]


In [5]:
y=np.random.randint(0,11,4)
print("vector-2")
print(y)


vector-2
[7 7 2 8]


In [6]:
print("arrange 3x4 matric with 10-21 values")
m=np.arange(10,22).reshape((3,4))
print(m)

arrange 3x4 matric with 10-21 values
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [9]:
print("finding no of rows and colums of a given matrix")
m=np.arange(0,10).reshape((2,5))
print(m)

print("no of rows and colums:")
print(m.shape)

finding no of rows and colums of a given matrix
[[0 1 2 3 4]
 [5 6 7 8 9]]
no of rows and colums:
(2, 5)


In [11]:
import numpy as np
print(" creating 3x3 matrix with diagonla=1,remaing =0")
x=np.eye(3)
print(x)

print(" creating 4x4 matrix with diagonla=1,remaing =0")
y=np.eye(4)
print(y)

 creating 3x3 matrix with diagonla=1,remaing =0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 creating 4x4 matrix with diagonla=1,remaing =0
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
print(x)
#except border remaing as 0


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
print("5x5 zero matrix with diagonal elements =1,2,3,4,5")
n=np.diag([1,2,3,4,5])
print(n)

x=np.diag([3,8,10])
print(x)

5x5 zero matrix with diagonal elements =1,2,3,4,5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[ 3  0  0]
 [ 0  8  0]
 [ 0  0 10]]


In [14]:
print("4x4 in which 0-1 are staggared ,eith zeros on the main diagonal")
x=np.zeros((4,4))
x[::2, 1::2]=1
x[1::2, ::2]=1
print(x)

4x4 in which 0-1 are staggared ,eith zeros on the main diagonal
[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [15]:
print("3x3x3 matrix with random values")
x=np.random.random((3,3,3,))
print(x)

3x3x3 matrix with random values
[[[0.54310914 0.83533671 0.84695944]
  [0.76118138 0.94516032 0.92159754]
  [0.50243036 0.1886428  0.3250628 ]]

 [[0.18565935 0.50383743 0.54566137]
  [0.40864227 0.73922642 0.06020175]
  [0.41898551 0.89380209 0.96318414]]

 [[0.29609527 0.81868541 0.17167762]
  [0.72669508 0.53942508 0.37637135]
  [0.4731352  0.13379121 0.19299361]]]


In [16]:
j=np.array([[0,1],[2,3]])
print("original array")
print(j)

print("sum of all elements:")
print(np.sum(j))

print("sum of each colum")
print(np.sum(j,axis=0))

print("sum of each row:")
print(np.sum(j,axis=1))

original array
[[0 1]
 [2 3]]
sum of all elements:
6
sum of each colum
[2 4]
sum of each row:
[1 5]


In [17]:
x=np.array([4,5])
y=np.array([7,10])

print("original array vectors:")
print(x)
print(y)

print("inner product of said vectors:")
print(np.dot(x,y))

original array vectors:
[4 5]
[ 7 10]
inner product of said vectors:
78


In [18]:
m=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,1,0])
print("original array")

print(v)
print("original matirx")
print(m)

result-np.empty_like(m)

for i in range(4):
    result[i, :]=m[i, :]+v
print("after adding the vector v to each row of the matrix m :")
print(result)

original array
[1 1 0]
original matirx
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ValueError: operands could not be broadcast together with shapes (4,) (4,3) 